'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Clinic_Sites
    Public Property Site_Code As String
    Public Property State As String
    Public Property County As String
    Public Property Year As Integer
    Public Property Start_Date As Nullable(Of Date)
    Public Property End_Date As Nullable(Of Date)

End Class
