'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Dental_Code_Costs
    Public Property Dental_Code As String
    Public Property Site_Code As String
    Public Property Year As Integer
    Public Property Cost As Nullable(Of Decimal)

End Class
