'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SurveyUserCost
    Public Property Record As Integer
    Public Property Dental_Code As String
    Public Property Quantity As Nullable(Of Integer)

End Class
