'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vw_Survey
    Public Property Record As Integer
    Public Property ChartNum As String
    Public Property Ethnicity_Desc As String
    Public Property Gender_Desc As String
    Public Property ZipCode As Nullable(Of Integer)
    Public Property Birthday As Nullable(Of Date)

End Class
